kill_signal = "SIGTERM"
kill_timeout = "2m0s"

# frp control plane
# frp HTTP server (for dashboard or HTTP tunnel)
[http_service]
  internal_port = 8080
  force_https = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

# frp KCP/QUIC server
[[services]]
  protocol = "udp"
  internal_port = 7000

  [[services.ports]]
    port = 7000
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

# frp TCP server
#[[services]]
#  protocol = "tcp"
#  internal_port = 7000
#
#  [[services.ports]]
#    port = 7000
#  [services.concurrency]
#    type = "connections"
#    hard_limit = 25
#    soft_limit = 20

# frp XTCP P2P (requires bind_addr = fly-global-services in frps.ini)
[[services]]
  protocol = "udp"
  internal_port = 7001

  [[services.ports]]
    port = 7001
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

# frp data plane
# frp TCP tunnel (example for Minecraft Java server, requires proxy_bind_addr = 0.0.0.0 (or :: in IPv6) in frps.ini)
[[services]]
  protocol = "tcp"
  internal_port = 25565

  [[services.ports]]
    port = 25565
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

# frp UDP tunnel (example for Minecraft Bedrock server, requires proxy_bind_addr = fly-global-services in frps.ini)
#[[services]]
#  protocol = "udp"
#  internal_port = 19132
#
#  [[services.ports]]
#    port = 19132
#  [services.concurrency]
#    type = "connections"
#    hard_limit = 25
#    soft_limit = 20