kill_signal = "SIGTERM"
kill_timeout = 120

# frp TCP server
[[services]]
  internal_port = 7000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 7000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "1m"
    restart_limit = 0
    timeout = "2s"

# frp KCP server
#[[services]]
#  internal_port = 7000
#  protocol = "udp"
#
#  [services.concurrency]
#    hard_limit = 25
#    soft_limit = 20
#    type = "connections"
#
#  [[services.ports]]
#    port = 7000

# frp dashboard and metrics
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "1m"
    restart_limit = 0
    timeout = "2s"

# frp TCP tunnel (example for Minecraft server)
[[services]]
  internal_port = 25565
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 25565

# frp UDP tunnel (example for torrent tracker, requires bind_addr = fly-global-services in frpc.ini)
[[services]]
  internal_port = 6969
  protocol = "udp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 6969